# Create a Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  # You can specify the namespace where you want to create the service account.
  # If you omit the namespace, it will be created in the default namespace.
  namespace: suseai

---

# # Create a ClusterRole
# # ClusterRole already exists, so you don't need to create.
# # But, if you want to create a custom ClusterRole, you can define like this.
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-admin-role
#   namespace: suseai
# rules:
# - apiGroups: ["*"]
#   resources: ["*"]
#   verbs: ["*"]

---

# Create a ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
  namespace: suseai
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: suseai # make sure this matches the namespace of the ServiceAccount
roleRef:
  kind: ClusterRole
  name: cluster-admin # Use the existing cluster-admin ClusterRole
  apiGroup: rbac.authorization.k8s.io
